spring.application.name=portfolio-backend
server.port=${PORT:8080}

# 1. DATABASE (Local default + Render Override)
spring.datasource.url=${DB_URL:jdbc:postgresql://localhost:5432/portfolio_db}
spring.datasource.username=${DB_USER:postgres}
spring.datasource.password=${DB_PASSWORD:root}
spring.jpa.hibernate.ddl-auto=create
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# 2. JWT (Local default + Render Override)
app.jwt.secret=${JWT_SECRET:local_dummy_secret_key_for_testing_only_1234567890}
app.jwt.expiration-ms=86400000
app.jwt.refresh-expiration-ms=604800000

# 3. EMAIL (Local default + Render Override)
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=${MAIL_USER:dummy_email@gmail.com}
spring.mail.password=${MAIL_PASSWORD:dummy_password}
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

# 4. REDIS (Local default + Render Override)
spring.data.redis.host=${REDIS_HOST:localhost}
spring.data.redis.port=${REDIS_PORT:6379}
# Agar Render wale Upstash Redis me password hai, toh neeche wali line se '#' hata dena aur Render me REDIS_PASSWORD add kar dena:
# spring.data.redis.password=${REDIS_PASSWORD}

# 5. CORS (Local Angular default + Render Vercel Override)
app.cors.allowed-origins=${FRONTEND_URL:http://localhost:4200}